# -*- coding: utf-8 -*-
"""heart_deployment.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19uIVC-CAXaYpfGI4JdnWtIn-xn3XS5_L
"""

import streamlit as st
import joblib

model = joblib.load("dtc_model.pkl")

st.title("Medical data set!")

age = st.number_input("Age")
gender = st.number_input("Gender")
heart_rate = st.number_input("Heart rate")
systolic_bp = st.number_input("Systolic blood pressure")
diastolic_bp = st.number_input("Diastolic blood pressure")
blood_sugar = st.number_input("Blood sugar")
ck_mb = st.number_input("CK-MB")
troponin = st.number_input("Troponin")
result = st.number_input("Result")

input_data = pd.DataFrame([[
    age,
    gender,
    heart_rate,
    systolic_bp,
    diastolic_bp,
    blood_sugar,
    ck_mb,
    troponin
]], columns=model.feature_names_in_)

if st.button("predict"):
    result = model.predict(input_data)[0]
    if result == "negative":
        st.success("Negative")
    else:
        st.error("Positive")
